language: go
env:
  - GO111MODULE=on
go:
  - 1.11.x
branches:
  only:
    - develop
install: go get -v github.com/gohugoio/hugo
script: 
  - hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  on:
    branch: develop